plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.heychatgptassist'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.heychatgptassist"
        minSdk 31
        targetSdk 35
        versionCode 7
        versionName "0.7"
    }
}

dependencies {
    implementation "dev.rikka.shizuku:api:13.1.5"
    implementation "dev.rikka.shizuku:provider:13.1.5"
}
